### PR TITLE
xurls-bin PKGBUILD

### PR DESCRIPTION
**Pull request by pellettiero**

### CODE REVIEW

**Comment by mvdan** [comment]
This is just replacing the existing PKGBUILD with another, so it won't work as-is. I guess I'll just do it myself in a separate repo.

Also, why the suport for x86 and arm? Arch doesn't support arm and will drop x86 soon.

**Comment by pellettiero** [comment]
arm should be for Arch Linux ARM (packages for e.g. Raspberry Pi), but I don't know if the AUR is used for it.
You're right though, I just grabbed all linux packages, sorry :man_facepalming:

**Comment by mvdan** [comment]
Yes please, remove all but amd64.

**Comment by pellettiero** [comment]
Done!

**Comment by mvdan** [comment]
As said previously, this is replacing the regular package so I can't merge it.

I have multiple packages for Go programs of mine, so I'll look at making `-bin` versions of all of them at once.

Thanks for your help!

**Comment by pellettiero** [comment]
Oh, alright then.
Cheers mate!

**Pull request closed without merging**
